# Generated by Django 4.2.16 on 2024-12-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
