# Generated by Django 4.2.16 on 2024-12-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_employee_age_alter_employee_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
