# Generated by Django 4.2.16 on 2025-01-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_attendance_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="check_in_time",
        ),
        migrations.AddField(
            model_name="attendance",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_out_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
