# Generated by Django 4.2.16 on 2025-01-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_remove_attendance_check_in_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="start_time",
            new_name="check_in_time",
        ),
    ]
