# Generated by Django 4.2.16 on 2025-01-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_rename_start_time_attendance_check_in_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
