# Generated by Django 4.2.16 on 2025-01-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
